= Universidad Nacional de General Sarmiento - Base de datos: Trabajo Práctico
Ferreyra Fernando <s@email>; Goñes Elías <s@email>; Oviedo Daniela <s@email>; Segretín Romina <s@email>
v1, {docdate}. Docentes Hernán Czemerinski - Hernán Rondelli
:toc: left
:toc-title: Contenidos
:numbered:

- Integrantes

* Ferreyra Fernando

* Goñes Elías

* Oviedo Daniela

* Segretín Romina


== Introducción


En el presente informe nos proponemos explicar el proceso transcurrido para dar respuesta a una situación planteada en el marco de la materia
_Bases de datos 1_. La situación planteada, consiste en modelar los datos usados para almacenar información de tarjetas de crédito. Luego, se usará este modelo en la implementación de dos aplicaciones CLI en Go. 
Nos proponemos mostrar los pasos realizados y dificultades en la realización de la base de datos que modeliza el almacenamiento
de información relativa a tarjetas de crédito, en la creación del archivo CLI implementado en Go y en la creación de otra base de datos BoltDB, también desde una aplicación CLI.
Desarrollaremos nuestra explicación en tres partes: _descripción de las tablas principales_, _Stored Procedures y Triggers_, y _Jason y Bases de datos NOSQL_. Finalmente, concluiremos nuestro informe con una reflexión grupal comparando el uso de las bases de datos SQL y NOSQL.


== Descripción del informe


=== Descripción de las tablas principales


==== Tarjetas de crédito


El sistema debe contar con un registro de compras realizadas con cada tarjeta. Cada tarjeta le pertenece a un cliente (a excepción de dos clientes que tendrán dos). Los clientes realizan compras en comercios a través de su tarjeta.
Las tarjetas de crédito son el medio para realizar una compra. Las tarjetas de crédito no tienen extensiones. 
Los usuaries no tienen permitido financiar sus compras en cuotas, todo en un solo pago. Una tarjeta de crédito puede ser suspendida
si recibe dos rechazos por límite de compra en un mismo día.
Además, las tarjetas presentan las siguientes características:

* Número de tarjeta.
* Número de cliente.
* Tiempo inicial y final de validez.
* Código de seguridad.
* Límite de compra.
* Estado de la tarjeta ("vigente", "suspendida", "anulada").


==== Cliente


Los clientes realizan compras con la tarjeta. Le cliente no puede tener más de una tarjeta.
Un cliente es alertado por posibles fraudes tales como, realizar una compra en una lapso de tiempo muy bajo en diferentes
ubicaciones (menos de un minuto si es en el mismo código postal, cinco minutos si es en diferentes códigos postales), 
también un cliente es alertado si recibe dos rechazos de límite de compra en un mismo día, seguido de una suspensión preventiva de la tarjeta.

Un cliente tiene las siguientes características:

* Número de cliente.
* Nombre y apellido.
* Domicilio.
* Teléfono.


==== Compra


La compra se encarga de guardar los datos que implican dicha acción. Los datos son:

* Número de operación.
* Número de tarjeta.
* Número de comercio.
* Fecha de realización.
* Monto.
* Estado de la compra ("pagado" o "no pagado").

Para finalizar la introducción, este documento tiene como objetivo presentar los detalles del trabajo práctico.
Éste contiene un resumen de las principales funciones realizadas en los distintos lenguajes de programación. 
Además se muestran los problemas encontrados con sus respectivas soluciones.


=== Stored Procedures y triggers


El sistema fue construido con los lenguajes _Go_ y _Pl/pgSQL_. El modelo de datos relativa a tarjetas de créditos son almacenadas en 
la base de datos relacional _PostgreSQL_. Por último, en _BoltDB_ se guardan datos de clientes, comercios,
 tarjetas y compras para comparar el modelo relacional con un modelo no relacional (_NoSQL_).

Las funciones creadas tienen como objetivo vincular al usuarie con la base de datos. La forma de interactuar es a través 
de una interfaz de líneas de comandos.

* _autorizar_compra_ 

Recibe los datos de una posible compra (número de tarjeta, código de seguridad, número de comercio, 
monto a pagar). La función retorna _true_ si se aprueba y _false_ si ocurre lo contrario.

Para autorizar una compra la función controla que se cumplan los siguientes requisitos: La tarjeta debe existir y debe estar 
en vigencia. La compra no debe superar el límite de compra (para eso se le suma las anteriores compras). La terjeta
no debe estar suspendida.

ESta función, devuelve el booleano correspondiente a si la tarjeta es vigente o no.

* _func_generar_resumen

Recibe los datos del cliente con su período del año y genera un resumen con todas las compras y el total a pagar.

* _func_alerta_rechazo_

Esta función es ejecutada cuando se genera un rechazo al autorizar la compra. Se encarga de registrar el rechazo en una 
tabla de alertas. Si un cliente tuvo dos rechazos por superar el límite de compra en un día, la función establece una
suspensión de la tarjeta seguido de una alerta. Se implementa usando un trigger.

Esta función es ejecutada por el trigger _rechazo_trig_:

* _func_alerta_compra_

Esta función es ejecutada cuando se realiza una compra. Controla que no se realicen dos compras en un lapso menor a 1 minuto 
es dentro del código postal y un lapso de 5 minutos de en fuera del código postal. En caso de que se cumpla, la función registra 
la alerta._ Se implementa usando un tigger.

==== Problemas encontrados

* Un problema que se presentó fue que cuando se intentó hacer los triggers no se sabía cómo hacer para que recorra
 la tabla para tomar los valores de las fechas para comparar. En un principio se intentó hacer una clausura que dé las fechas 
 que se pedía, pero no funcionó. Luego se optó por obtener todas las fechas de la tarjeta que se necesitaba en un record y 
 hacerle un for para obtener cada fecha y comparar.

* Cuando se estaba haciendo el trigger de compras, a la hora de hacer el insert en la tabla _alerta_, nos dimos cuanta que no 
teníamos el dato del _nrorechazo_ porque el trigger se activaba cuando se reliza una compra y no un rechazo, lo cual daba error. Se solucionó dejándolo en null.

* Otro problema encontrado fue a la hora de realizar la suma de las compras para autorizar la nueva compra, no estábamos 
verificando que el valor del campo _monto_ se encuentre vacío y entonces tiraba error a la hora de calcular la suma total de 
las compras previas mas el valor del nuevo monto, la solución fue controlar que existan compras previas para una determinada
 tarjeta antes de realizar la suma.

* También se presentaron problemas al realizar la función _genera_resumen_. Al principio se buscó realizar un algoritmo que realice el producto cartesiano entre las tablas tarjeta, cierre, cliente, compra y comercio. 
Filtrando luego, de acuerdo a las condiciones pedidas. Pero, no pudimos desarrollar el algoritmo que permita extraer la información obtenida de esta tabla 
filtrada, para guardarla luego en las tablas cabecera y resumen. Luego, se realizaron funciones auxiliares con la finalidad
de extraer la información necesaria para complatar las tablas _cabecera_ y _detalle_, guardándola en una tabla que luego usaríamos como auxiliar. 
Finalmente, comprendimos que esta forma no era la más óptima y decidimos ir seleccionando la información a medida que se consultaban las 
tablas expuestas. De esta manera, el código presentado muestra una mayor claridad y compacidad.  

* Hubo un problema para recorrer la tabla consumos. Cuando se recorre cada fila de la tabla se llama a la función _autorizar_compra_.
El problema estaba en la forma de llamar a la función (con un select). Esta forma de llamar obliga a retornar un valor, porque
la función devuelve un booleano. Para solucionar eso se remplazó por _perform_ que cumple una función como _select_ pero
no pide devolución de valor.

=== JSON y bases de datos NoSQL

Para guardar valores en los buckets primero creamos variables de tipo struct con las diferentes entidades y con sus respectivos
atributos. Luego esos valores son pasados a formato JSON para que en el próximo paso sean guardados en buckets. En los buckets
van el elemento JSON, el nombre del bucket y una clave para identificar.

== Implementación

[source, go]
----
//IMPLEMENTACIÓN DE CLI.GO

----

[source, go]
----
//IMPLEMENTACIÓN DE NOSQL.GO

package main

import (
	"encoding/json"
	"fmt"
	bolt "github.com/coreos/bbolt"
	"log"
	"strconv"
)

type Cliente struct {
	Nrocliente int
	Nombre     string
	Apellido   string
	Domicilio  string
	Telefono   string
}

type Tarjeta struct {
	Nrotarjeta   string
	Nrocliente   int
	Validadesde  string
	Validahasta  string
	Codseguridad string
	Limitecompra float64
	Estado       string
}

type Comercio struct {
	Nrocomercio  int
	Nombre       string
	Domicilio    string
	Codigopostal string
	Telefono     string
}

type Compra struct {
	Nrooperacion int
	Nrotarjeta   string
	Nrocomercio  int
	Fecha        string
	Monto        float64
	Pagado       bool
}

func CreateUpdate(dbb *bolt.DB, bucketName string, key []byte, val []byte) error {

	tx, err := dbb.Begin(true)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	b, _ := tx.CreateBucketIfNotExists([]byte(bucketName))

	err = b.Put(key, val)
	if err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	return nil
}

func ReadUnique(dbb *bolt.DB, bucketName string, key []byte) ([]byte, error) {
	var buf []byte

	err := dbb.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte(bucketName))
		buf = b.Get(key)
		return nil
	})
	return buf, err
}

func cargar_datos() {

	dbb, err := bolt.Open("dbnosql.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer dbb.Close()

	//Hago todos las variables structs

	cliente1 := Cliente{1, "Jose Maria", "Perez", "Av. T de Alvear 1299", "541126598745"}
	cliente2 := Cliente{2, "Roberto", "Rafaela", "Azcuenaga 548", "541146598787"}
	cliente3 := Cliente{3, "Cecilia", "Suarez", "Salta 1210", "541126498789"}

	comercio1 := Comercio{4, "Lo de Tito", "Vivaldi 339", "C1456NSM", "541178955412"}
	comercio2 := Comercio{5, "Moncho", "Catamarca 138", "B1600KIB", "541185749688"}
	comercio3 := Comercio{6, "Tecnico el Chapu", "Canal Beagle 1708", "B1610OIB", "541165754648"}

	tarjeta1 := Tarjeta{"4286283215095190", 1, "201709", "202208", "114", 45000.00, "vigente"}
	tarjeta2 := Tarjeta{"4532449515464319", 2, "202001", "202412", "881", 30000.00, "vigente"}
	tarjeta3 := Tarjeta{"4716905901199213", 3, "202108", "202607", "311", 15000.00, "vigente"}

	compra1 := Compra{7, "4286283215095190", 1, "2021-06-12", 293, true}
	compra2 := Compra{8, "4532449515464319", 2, "2021-06-11", 1800, true}
	compra3 := Compra{9, "4716905901199213", 3, "2021-06-13", 5500, true}

	//Paso todo a JSON

	datacl1, err := json.Marshal(cliente1)
	if err != nil {
		log.Fatal(err)
	}

	datacl2, err := json.Marshal(cliente2)
	if err != nil {
		log.Fatal(err)
	}

	datacl3, err := json.Marshal(cliente3)
	if err != nil {
		log.Fatal(err)
	}

	dataco1, err := json.Marshal(comercio1)
	if err != nil {
		log.Fatal(err)
	}

	dataco2, err := json.Marshal(comercio2)
	if err != nil {
		log.Fatal(err)
	}

	dataco3, err := json.Marshal(comercio3)
	if err != nil {
		log.Fatal(err)
	}

	datata1, err := json.Marshal(tarjeta1)
	if err != nil {
		log.Fatal(err)
	}

	datata2, err := json.Marshal(tarjeta2)
	if err != nil {
		log.Fatal(err)
	}

	datata3, err := json.Marshal(tarjeta3)
	if err != nil {
		log.Fatal(err)
	}

	datacpra1, err := json.Marshal(compra1)
	if err != nil {
		log.Fatal(err)
	}

	datacpra2, err := json.Marshal(compra2)
	if err != nil {
		log.Fatal(err)
	}

	datacpra3, err := json.Marshal(compra3)
	if err != nil {
		log.Fatal(err)
	}

	//Creo los buckets

	CreateUpdate(dbb, "cliente1", []byte(strconv.Itoa(cliente1.Nrocliente)), datacl1)
	CreateUpdate(dbb, "cliente2", []byte(strconv.Itoa(cliente2.Nrocliente)), datacl2)
	CreateUpdate(dbb, "cliente3", []byte(strconv.Itoa(cliente3.Nrocliente)), datacl3)

	CreateUpdate(dbb, "comercio1", []byte(strconv.Itoa(comercio1.Nrocomercio)), dataco1)
	CreateUpdate(dbb, "comercio2", []byte(strconv.Itoa(comercio2.Nrocomercio)), dataco2)
	CreateUpdate(dbb, "comercio3", []byte(strconv.Itoa(comercio3.Nrocomercio)), dataco3)

	CreateUpdate(dbb, "tarjeta1", []byte(tarjeta1.Nrotarjeta), datata1)
	CreateUpdate(dbb, "tarjeta2", []byte(tarjeta2.Nrotarjeta), datata2)
	CreateUpdate(dbb, "tarjeta3", []byte(tarjeta3.Nrotarjeta), datata3)

	CreateUpdate(dbb, "compra1", []byte(strconv.Itoa(compra1.Nrooperacion)), datacpra1)
	CreateUpdate(dbb, "compra2", []byte(strconv.Itoa(compra2.Nrooperacion)), datacpra2)
	CreateUpdate(dbb, "compra3", []byte(strconv.Itoa(compra3.Nrooperacion)), datacpra3)

	//Leo los buckets

	resultado1, err := ReadUnique(dbb, "cliente1", []byte(strconv.Itoa(cliente1.Nrocliente)))
	fmt.Printf("%s\n", resultado1)
	resultado2, err := ReadUnique(dbb, "cliente2", []byte(strconv.Itoa(cliente2.Nrocliente)))
	fmt.Printf("%s\n", resultado2)
	resultado3, err := ReadUnique(dbb, "cliente3", []byte(strconv.Itoa(cliente3.Nrocliente)))
	fmt.Printf("%s\n", resultado3)

	resultado4, err := ReadUnique(dbb, "comercio1", []byte(strconv.Itoa(comercio1.Nrocomercio)))
	fmt.Printf("%s\n", resultado4)
	resultado5, err := ReadUnique(dbb, "comercio2", []byte(strconv.Itoa(comercio2.Nrocomercio)))
	fmt.Printf("%s\n", resultado5)
	resultado6, err := ReadUnique(dbb, "comercio3", []byte(strconv.Itoa(comercio3.Nrocomercio)))
	fmt.Printf("%s\n", resultado6)

	resultado7, err := ReadUnique(dbb, "tarjeta1", []byte(tarjeta1.Nrotarjeta))
	fmt.Printf("%s\n", resultado7)

}

func main() {

	var tecla_uno int

	fmt.Println("\n-------------------------------\nPresiona el num 1 para cargar y leer los datos")

	fmt.Scan(&tecla_uno)

	if tecla_uno == 1 {
		cargar_datos()

	} else {
		fmt.Println("Error, ingresa nuevamente")
		main()
	}
}

----


== Conclusión

Una de las diferencias entre los modelos de datos SQL y NoSQL radica en la forma de hacer consultas. En NoSQL puede ser más complejo
agrupar elementos porque no hay relación. La forma de hacer consultas es a través de la clave y el valor.

Otra diferencia es la manera de crear la estructura de datos. Por un lado tenemos la base de datos SQL donde se crean tablas
que pueden estar relacionadas con otras. Y por el otro lado, la base de datos NoSQL se modela con elementos clave/valor.

