= Base de datos: Trabajo Práctico
:toc:
:toc-title: Contenidos
:numbered:

== Integrantes

* Ferreyra Fernando.
* Goñez Elías.
* Oviedo Daniela.
* Segretin Romina.



== Introducción

El trabajo práctico solicita la creación de una base de datos para un sistema de tarjetas de crédito. 

El sistema debe contar con un registro de compras realizadas con cada tarjeta. Cada tarjeta le pertenece a un cliente (a excepción de dos clientes que tendrán dos). Los clientes realizan compras en comercios a través de su tarjeta.

=== Tarjetas de crédito

Las tarjetas de crédito son el medio para realizar una compra. Las tarjetas de crédito no tienen extensiones. 
Los usuaries no tienen permitido financiar sus compras en cuotas, todo en un solo pago. Una tarjeta de crédito puede ser suspendida
si recibe dos rechazos por límite de compra en un mismo día.
Además, las tarjetas presentan las siguientes características:

* Número de tarjeta.
* Número de cliente.
* Tiempo inicial y final de validez.
* Código de seguridad.
* Límite de compra.
* Estado de la tarjeta ("vigente", "suspendida", "anulada").



=== Cliente

Los clientes realizan compras con la tarjeta. Le cliente no puede tener más de una tarjeta.
Un cliente es alertado por posibles fraudes tales como, realizar una compra en una lapso de tiempo muy bajo en diferentes
ubicaciones (menos de un minuto si es en el mismo código postal, cinco minutos si es en diferentes códigos postales), 
también un cliente es alertado si recibe dos rechazos de límite de compra en un mismo día, seguido de una suspensión preventiva de la tarjeta.

Un cliente tiene las siguientes características:

* Número de cliente.
* Nombre y apellido.
* Domicilio.
* Teléfono.

=== Compra

La compra se encarga de guardar los datos que implican dicha acción. Los datos son:

* Número de operación.
* Número de tarjeta.
* Número de comercio.
* Fecha de realización.
* Monto.
* Estado de la compra ("pagado" o "no pagado").

Para finalizar la introducción, este documento tiene como objetivo presentar los detalles del trabajo práctico.
Éste contiene un resumen de las principales funciones realizadas en los distintos lenguajes de programación. 
Además se muestran los problemas encontrados con sus respectivas soluciones.

== Desarrollo

El sistema fue construido con los lenguajes _Go_ y _Pl/pgSQL_. El modelo de datos relativa a tarjetas de créditos son almacenadas en 
la base de datos relacional _PostgreSQL_. Por último, en _BoltDB_ se guardan datos de clientes, comercios,
 tarjetas y compras para comparar el modelo relacional con un modelo no relacional (_NoSQL_).

=== Funciones

Las funciones creadas tienen como objetivo vincular al usuarie con la base de datos. La forma de interactuar es a través 
de una interfaz de líneas de comandos.

* _autorizar_compra_ 

Recibe los datos de una posible compra (número de tarjeta, código de seguridad, número de comercio, 
monto a pagar). La función retorna _true_ si se aprueba y _false_ si ocurre lo contrario.

Para autorizar una compra la función controla que se cumplan los siguientes requisitos: La tarjeta debe existir y debe estar 
en vigencia. La compra no debe superar el límite de compra (para eso se le suma las anteriores compras). La terjeta
no debe estar suspendida.

* _func_generar_resumen

Recibe los datos del cliente con su período del año y genera un resumen con todas las compras y el total a pagar.

* _func_alerta_rechazo_

Esta función es ejecutada cuando se genera un rechazo al autorizar la compra. Se encarga de registrar el rechazo en una 
tabla de alertas. Si un cliente tuvo dos rechazos por superar el límite de compra en un día, la función establece una
suspensión de la tarjeta seguido de una alerta.

* _func_alerta_compra

Esta función es ejecutada cuando se realiza una compra. Controla que no se realicen dos compras en un lapso menor a 1 minuto 
es dentro del código postal y un lapso de 5 minutos de en fuera del código postal. En caso de que se cumpla, la función registra 
la alerta._



== Problemas encontrados

* Un problema que se presentó fue que cuando se intentó hacer los triggers no se sabía cómo hacer para que recorra
 la tabla para tomar los valores de las fechas para comparar. En un principio se intentó hacer una clausura que dé las fechas 
 que se pedía, pero no funcionó. Luego se optó por obtener todas las fechas de la tarjeta que se necesitaba en un record y 
 hacerle un for para obtener cada fecha y comparar.

* Cuando se estaba haciendo el trigger de compras, a la hora de hacer el insert en la tabla _alerta_, nos dimos cuanta que no 
teníamos el dato del _nrorechazo_ porque el trigger se activaba cuando se reliza una compra y no un rechazo, lo cual daba error. Se solucionó dejándolo en null.

* Otro problema encontrado fue a la hora de realizar la suma de las compras para autorizar la nueva compra, no estábamos 
verificando que el valor del campo _monto_ se encuentre vacío y entonces tiraba error a la hora de calcular la suma total de 
las compras previas mas el valor del nuevo monto, la solución fue controlar que existan compras previas para una determinada
 tarjeta antes de realizar la suma.
 
== Comparación entre SQL y NoSQL



