= Base de datos: Trabajo Práctico
:toc:
:toc-title: Contenidos
:numbered:

== Integrantes

* Ferreyra Fernando.
* Goñez Elías.
* Oviedo Daniela.
* Segretin Romina.



== Introducción

El trabajo práctico solicita la creación de una base de datos para un sistema de tarjetas de crédito. 

El sistema debe contar con un registro de compras realizadas con cada tarjeta. Cada tarjeta le pertenece a un cliente (a excepción de dos clientes que tendrán dos). Los clientes realizan compras en comercios a través de su tarjeta.

=== Tarjetas de crédito

Las tarjetas de crédito son el medio para realizar una compra. Las tarjetas de crédito no tienen extensiones. 
Los usuaries no tienen permitido financiar sus compras en cuotas, todo en un solo pago. Una tarjeta de crédito puede ser suspendida
si recibe dos rechazos por límite de compra en un mismo día.
Además, las tarjetas presentan las siguientes características:

* Número de tarjeta.
* Número de cliente.
* Tiempo inicial y final de validez.
* Código de seguridad.
* Límite de compra.
* Estado de la tarjeta ("vigente", "suspendida", "anulada").



=== Cliente

Los clientes realizan compras con la tarjeta. Le cliente no puede tener más de una tarjeta.
Un cliente es alertado por posibles fraudes tales como, realizar una compra en una lapso de tiempo muy bajo en diferentes
ubicaciones (menos de un minuto si es en el mismo código postal, cinco minutos si es en diferentes códigos postales), 
también un cliente es alertado si recibe dos rechazos de límite de compra en un mismo día, seguido de una suspensión preventiva de la tarjeta.

Un cliente tiene las siguientes características:

* Número de cliente.
* Nombre y apellido.
* Domicilio.
* Teléfono.

=== Compra

La compra se encarga de guardar los datos que implican dicha acción. Los datos son:

* Número de operación.
* Número de tarjeta.
* Número de comercio.
* Fecha de realización.
* Monto.
* Estado de la compra ("pagado" o "no pagado").

Para finalizar la introducción, este documento tiene como objetivo presentar los detalles del trabajo práctico.
Éste contiene un resumen de las principales funciones realizadas en los distintos lenguajes de programación. 
Además se muestran los problemas encontrados con sus respectivas soluciones.

== Desarrollo

El sistema fue construido con los lenguajes Go y Pl/pgSQL. El modelo de datos relativa a tarjetas de créditos son almacenadas en 
la base de datos relacional PostgreSQL. Por último, en BoltDB se guardan datos de clientes, comercios,
 tarjetas y compras para comparar el modelo relacional con un modelo relacional (NoSQL).

=== Pl/pgsSQL



== Problemas encontrados

Un problema que se presentó fue que cuando se intentó hacer los triggers no se sabía cómo hacer para que recorra
 la tabla para tomar los valores de las fechas para comparar. En un principio se intentó hacer una clausura que dé las fechas 
 que se pedía, pero no funcionó. Luego se optó por obtener todas las fechas de la tarjeta que se necesitaba en un record y 
 hacerle un for para obtener cada fecha y comparar.

Cuando se estaba haciendo el trigger de compras, que pasar hacer insert en la tabla alerta, como se necesita un nrorechazo y 
el trigger se activaba cuando se reliza una compra y no un rechazo, no teníamos el dato. Se solucionó dejándolo en null.

Otro problema encontrado fue a la hora de realizar la suma de las compras para autorizar la nueva compra, no estábamos 
verificando que el valor del campo monto se encuentre vacío y entonces tiraba error a la hora de calcular la suma total de 
las compras previas mas el valor del nuevo monto, la solución fue controlar que existan compras previas para una determinada
 tarjeta antes de realizar la suma.

