= Base de datos: Tarjetas de crédito

- Integrantes

* Ferreyra Fernando

* Goñes Elías

* Oviedo Daniela

* Segretín Romina


== Introducción


En el presente informe nos proponemos explicar el proceso transcurrido para dar respuesta a una situación planteada en el marco de la materia
_Bases de datos 1_. La situación planteada, consiste en modelar los datos usados para almacenar información de tarjetas de crédito. Luego, se usará este modelo en la implementación de dos aplicaciones en Go. 
Nos proponemos mostrar los pasos para la realización de la base de datos que modeliza el almacenamiento de información relativa a tarjetas de crédito, en la creación del archivo implementado en Go y en la creación de otra base de datos BoltDB, también desde una aplicación en GO.
Desarrollaremos nuestra explicación en tres partes: _descripción de las tablas principales_, _Stored Procedures y Triggers_, y _Jason y Bases de datos NOSQL_.


== Descripción


=== Tablas principales


==== Tarjetas de crédito


El sistema debe contar con un registro de compras realizadas con cada tarjeta. Cada tarjeta le pertenece a un cliente (a excepción de dos clientes que tendrán dos). Los clientes realizan compras en comercios a través de su tarjeta.
Las tarjetas de crédito son el medio para realizar una compra. Las tarjetas de crédito no tienen extensiones. 
Los usuaries no tienen permitido financiar sus compras en cuotas, todo en un solo pago. Una tarjeta de crédito puede ser suspendida
si recibe dos rechazos por límite de compra en un mismo día.
Además, las tarjetas presentan las siguientes características:

* Número de tarjeta.
* Número de cliente.
* Tiempo inicial y final de validez.
* Código de seguridad.
* Límite de compra.
* Estado de la tarjeta ("vigente", "suspendida", "anulada").


==== Cliente


Los clientes realizan compras con la tarjeta. Le cliente no puede tener más de una tarjeta.
Un cliente es alertado por posibles fraudes tales como, realizar una compra en una lapso de tiempo muy bajo en diferentes
ubicaciones (menos de un minuto si es en el mismo código postal, cinco minutos si es en diferentes códigos postales), 
también un cliente es alertado si recibe dos rechazos de límite de compra en un mismo día, seguido de una suspensión preventiva de la tarjeta.

Un cliente tiene las siguientes características:

* Número de cliente.
* Nombre y apellido.
* Domicilio.
* Teléfono.


==== Compra


La compra se encarga de guardar los datos que implican dicha acción. Los datos son:

* Número de operación.
* Número de tarjeta.
* Número de comercio.
* Fecha de realización.
* Monto.
* Estado de la compra ("pagado" o "no pagado").

Para finalizar la introducción, este documento tiene como objetivo presentar los detalles del trabajo práctico.
Éste contiene un resumen de las principales funciones realizadas en los distintos lenguajes de programación. 
Además se muestran los problemas encontrados con sus respectivas soluciones.


=== Stored Procedures y triggers


El sistema fue construido con los lenguajes _Go_ y _Pl/pgSQL_. El modelo de datos relativa a tarjetas de créditos son almacenadas en 
la base de datos relacional _PostgreSQL_. Por último, en _BoltDB_ se guardan datos de clientes, comercios,
 tarjetas y compras para comparar el modelo relacional con un modelo no relacional (_NoSQL_).

Las funciones creadas tienen como objetivo vincular al usuarie con la base de datos. La forma de interactuar es a través 
de una interfaz de líneas de comandos.

* _autorizar_compra_ 

Recibe los datos de una posible compra (número de tarjeta, código de seguridad, número de comercio, 
monto a pagar). La función retorna _true_ si se aprueba y _false_ si ocurre lo contrario.

Para autorizar una compra la función controla que se cumplan los siguientes requisitos: La tarjeta debe existir y debe estar 
en vigencia. La compra no debe superar el límite de compra (para eso se le suma las anteriores compras). La tarjeta
no debe estar suspendida, ni encontrarse anulada para eso agregamos una condición mas que verifica ese estado.

Esta función, utiliza una función auxiliar que verifica la vigencia de las tarjetas y en caso que devuelva false no se autoriza la compra.

* _func_generar_resumen

Recibe los datos del cliente con su período del año y genera un resumen con todas las compras y el total a pagar.

* _func_alerta_rechazo_

Esta función es ejecutada cuando se genera un rechazo al autorizar la compra. Se encarga de registrar el rechazo en una 
tabla de alertas. Si un cliente tuvo dos rechazos por superar el límite de compra en un día, la función establece una
suspensión de la tarjeta seguido de una alerta. Se implementa usando un trigger.

Esta función es ejecutada por el trigger _rechazo_trig_:

* _func_alerta_compra_

Esta función es ejecutada cuando se realiza una compra. Controla que no se realicen dos compras en un lapso menor a 1 minuto 
es dentro del código postal y un lapso de 5 minutos de en fuera del código postal. En caso de que se cumpla, la función registra 
la alerta._ Se implementa usando un tigger.
